### ISSUE TITLE
Small typo in the config files

### ISSUE THREAD

**Issue by ChennyDeng** [elliottwu/MagicPony#2]
Hi Elliott,

Thanks for this amazing work! Your work is really inspiring, and I am trying to reproduce the code. I have identified a small typo in the config files. If we follow the scripts in results/ in the readme, then the relevant pretrained quadruped models will be downloaded to results/quadrupeds/ file. In this case, we might need to change the checkpoint_dir path in the relevant config file to 'results/quadrupeds' instead of 'results/quadupeds.'

Other than this, everything works perfectly! Thank you so much for providing such an amazing tool to reconstruct animals in the wild; it's super helpful. I truly appreciate your effort in organizing this well-written documentation. Wishing you a lovely day!

Chenny

**Comment by elliottwu** [comment]
Thanks for raising this! Should be fixed now!
