### ISSUE TITLE
How to create own dataset

### ISSUE THREAD

**Issue by zhou1234dd** [elliottwu/MagicPony#5]
Hello, thank you very much for sharing your code. If I want to train my own dataset, how should I create my own dataset?

**Comment by kim-sehun** [comment]
what is feat16 image file in the dataset??? How do I generate the image?

**Comment by elliottwu** [comment]
We've released the preprocessing code here: [data/preprocessing](https://github.com/elliottwu/MagicPony/tree/main/data/preprocessing). Sorry for the delay!
