### ISSUE TITLE
dino feature datasets

### ISSUE THREAD

**Issue by huizhoug** [elliottwu/MagicPony#8]
Hello, may I ask if it is possible to share the code for creating your dino feature datasets? Thank you

**Comment by elliottwu** [comment]
We've released the preprocessing code here: [data/preprocessing](https://github.com/elliottwu/MagicPony/tree/main/data/preprocessing). Sorry for the delay!

**Comment by huizhoug** [comment]
Thank you for your reply

**Comment by huizhoug** [comment]
Thank you for your reply！
